### ISSUE TITLE
Documentation update 2022 March 29

### ISSUE THREAD

**Issue by Ashark** [b3n0y/ResolveDevDoc#3]
Hi. With DR 18.0b1 they updated documentation. I have attached the new version and the current version for your convenience.

[README 20211021.txt](https://github.com/b3n0y/ResolveDevDoc/files/8550459/README.20211021.txt)
[README 20220329.txt](https://github.com/b3n0y/ResolveDevDoc/files/8550460/README.20220329.txt)

**Comment by b3n0y** [comment]
Thanks, I updated the API doc.
